[project]
name = 'Galactic-Ecosystem-Synchronization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cross-planet-effects]
path = 'contracts/cross-planet-effects.clar'
clarity_version = 2
epoch = 2.5

[contracts.ecosystem-parameters]
path = 'contracts/ecosystem-parameters.clar'
clarity_version = 2
epoch = 2.5

[contracts.species-interactions]
path = 'contracts/species-interactions.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
